set.seed(123)


###################################
#  Simulate different sources of heterochrony
###################################

###
#@title Simulate internal clocks
#@description: generates curves of biological age over chronological time
#@param: epsA is the spread of slopes
#@param: epsB is the spread of starting time points
#@param: ks is the average rate of maturation
#@param: tp are the time points at which the biological ages are returned.  Note that they should be monotonically increasing.
#@param: mode- 1 produces linear biological ages, with random starts and slopes
#              2 produces biological ages generated by a Gaussian process
#              3 produces biological ages generated by a Gamma process, what we end up using in the paper
#@param: n is the number of individuals simulated


simulateInternalClocks<-function(epsA, epsB, ks=c(0.8, 1, 1.2), tp=c(0,30), mode=1, n=100){
  #generate n internal clocks for each external clock
  
  
  internalClocks=lapply(ks, function(k){
    if(mode==1){
      #generate linear clocks, with varying slopes
      beta=rnorm(n, tp[1], epsB)*(k)
      alpha=abs(rnorm(n, k, epsA))
      sapply(1:n, function(i){
        seq(beta[i], length.out=(max(tp)-min(tp)), by=alpha[i])
      })
    }else{
      if(mode==2){
        #generate daily growth drawn from a normal distribution
        beta=rnorm(n, tp[1], epsB)*(k)
        #out1=sapply(1:n, function(i){
        #  seq(beta[i], length.out=(max(tp)-min(tp)), by=k)
        #})
        out1=sapply(1:n, function(i){
          rep(beta[i], length.out=(max(tp)-min(tp)))
        })
        
        alphas=matrix(k*rtruncnorm(n = n * ((max(tp)-min(tp)) - 1), sd = epsA, mean=1, a=0), n, (max(tp)-min(tp))-1)
        out2 = t(cbind(rep(0, n), t(apply(alphas, 1, cumsum))))
        
        out1+out2
      }else{
        if(mode==3){
          #gamma process
          
          scale=epsA
          shape=k/epsA
          
          
          beta=rnorm(n, tp[1], epsB)*(k)
          out1=sapply(1:n, function(i){
            rep(beta[i], length.out=(max(tp)-min(tp)))
          })
          
          alphas=matrix(rgamma(n = n * ((max(tp)-min(tp)) - 1), scale = scale, shape=shape), n, (max(tp)-min(tp))-1)
          out2 = t(cbind(rep(0, n), t(apply(alphas, 1, cumsum))))
          
          out1+out2
        }
      }
    }
    
  })
  
  internalClocks
}

#################################################
# Step 1:  Draw biological age vs chronological age, with starting time variation and maturation rate variation

#show ages
varyEpsBExperimentAges=simulateInternalClocks(epsA=0, epsB=1, n=1000, ks=c(0.5, 1, 1.5), tp=c(0:30))
varyEpsAExperimentAgesMode3=simulateInternalClocks(epsA=0.1, epsB=0, n=1000, tp=c(0,30), ks=c(0.5, 1, 1.5), mode=3)




pdf("plots/01_01_simulationBiologicalvsChronological.pdf", width=10, height=10)
par(mfcol = c(2,2))

plot(c(), c(), xlim=c(0,28), ylim=c(0,29), xlab="Chronological time (days)", ylab="Biological age (days)")
tp=rep(0:30)
cols=c(rgb(1, 0.5,0.5,1),rgb(1, 0.7,0.2,1), rgb(0.8, 0.6,1,1))
cols_transparent=c(rgb(1, 0.5,0.5,0.2),rgb(1, 0.7,0.2,0.2), rgb(0.8, 0.6,1,0.2))
apply(varyEpsBExperimentAges[[1]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[1])})
apply(varyEpsBExperimentAges[[2]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[2])})
apply(varyEpsBExperimentAges[[3]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[3])})
abline(c(0,0.5), col=cols[1], lwd=3)
abline(c(0,1), col=cols[2], lwd=3)
abline(c(0,1.5), col=cols[3], lwd=3)
abline(v=8, col="lightgreen", lty=3, lwd=3)
abline(v=13, col="forestgreen", lty=3, lwd=3)
abline(h=5, col="lightblue", lty=3, lwd=3)
abline(h=10, col="cornflowerblue", lty=3, lwd=3)

#interquartile ranges?

#vertical

rect(7.7, sort(varyEpsBExperimentAges[[1]][9,])[250], 8.3, sort(varyEpsBExperimentAges[[1]][9,])[750], col="lightgreen", lwd=2, border=cols[1])
rect(7.7, sort(varyEpsBExperimentAges[[2]][9,])[250], 8.3, sort(varyEpsBExperimentAges[[2]][9,])[750], col="lightgreen", lwd=2, border=cols[2])
rect(7.7, sort(varyEpsBExperimentAges[[3]][9,])[250], 8.3, sort(varyEpsBExperimentAges[[3]][9,])[750], col="lightgreen", lwd=2, border=cols[3])

rect(12.7, sort(varyEpsBExperimentAges[[1]][14,])[250], 13.3, sort(varyEpsBExperimentAges[[1]][14,])[750], col="forestgreen", lwd=2, border=cols[1])
rect(12.7, sort(varyEpsBExperimentAges[[2]][14,])[250], 13.3, sort(varyEpsBExperimentAges[[2]][14,])[750], col="forestgreen", lwd=2, border=cols[2])
rect(12.7, sort(varyEpsBExperimentAges[[3]][14,])[250], 13.3, sort(varyEpsBExperimentAges[[3]][14,])[750], col="forestgreen", lwd=2, border=cols[3])

#horizontal: do it properly with lm
i=sort(
  apply(varyEpsBExperimentAges[[1]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  })
)[c(250, 750)]
rect(i[1], 4.7, i[2], 5.3, col="lightblue", lwd=2, border=cols[1])
i=sort(
  apply(varyEpsBExperimentAges[[2]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  })
)[c(250, 750)]
rect(i[1], 4.7, i[2], 5.3, col="lightblue", lwd=2, border=cols[2])
i=sort(
  apply(varyEpsBExperimentAges[[3]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  })
)[c(250, 750)]
rect(i[1], 4.7, i[2], 5.3, col="lightblue", lwd=2, border=cols[3])





i=sort(
  apply(varyEpsBExperimentAges[[3]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(10)))[1]
  })
)[c(250, 750)]
rect(i[1], 9.7, i[2], 10.3, col="cornflowerblue", lwd=2, border=cols[3])


i=sort(
  apply(varyEpsBExperimentAges[[1]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(10)))[1]
  })
)[c(250, 750)]
rect(i[1], 9.7, i[2], 10.3, col="cornflowerblue", lwd=2, border=cols[1])
i=sort(
  apply(varyEpsBExperimentAges[[2]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(10)))[1]
  })
)[c(250, 750)]
rect(i[1], 9.7, i[2], 10.3, col="cornflowerblue", lwd=2, border=cols[2])



#legend(0, 30, rev(c("0.5", "1", "1.5")), col=rev(cols), lwd=1, title="maturation rate", bty="n")
legend(-1, 30, rev(c("0.5", "1", "1.5")), col=rev(cols), lwd=1, title="maturation \nrate", bty="o", box.col="white")


plot(c(), c(), xlim=c(0,28), ylim=c(0,29), xlab="Chronological time (days)", ylab="Biological age (days)")
tp=rep(0:30)
apply(varyEpsAExperimentAgesMode3[[1]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[1])})
apply(varyEpsAExperimentAgesMode3[[2]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[2])})
apply(varyEpsAExperimentAgesMode3[[3]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[3])})
abline(c(0,0.5), col=cols[1])
abline(c(0,1), col=cols[2])
abline(c(0,1.5), col=cols[3])
abline(v=8, col="lightgreen", lty=3, lwd=3)
abline(v=13, col="forestgreen", lty=3, lwd=3)
abline(h=5, col="lightblue", lty=3, lwd=3)
abline(h=10, col="cornflowerblue", lty=3, lwd=3)

#interquartile ranges?

#vertical

rect(7.7, sort(varyEpsAExperimentAgesMode3[[1]][9,])[250], 8.3, sort(varyEpsAExperimentAgesMode3[[1]][9,])[750], col="lightgreen", lwd=2, border=cols[1])
rect(7.7, sort(varyEpsAExperimentAgesMode3[[2]][9,])[250], 8.3, sort(varyEpsAExperimentAgesMode3[[2]][9,])[750], col="lightgreen", lwd=2, border=cols[2])
rect(7.7, sort(varyEpsAExperimentAgesMode3[[3]][9,])[250], 8.3, sort(varyEpsAExperimentAgesMode3[[3]][9,])[750], col="lightgreen", lwd=2, border=cols[3])

rect(12.7, sort(varyEpsAExperimentAgesMode3[[1]][14,])[250], 13.3, sort(varyEpsAExperimentAgesMode3[[1]][14,])[750], col="forestgreen", lwd=2, border=cols[1])
rect(12.7, sort(varyEpsAExperimentAgesMode3[[2]][14,])[250], 13.3, sort(varyEpsAExperimentAgesMode3[[2]][14,])[750], col="forestgreen", lwd=2, border=cols[2])
rect(12.7, sort(varyEpsAExperimentAgesMode3[[3]][14,])[250], 13.3, sort(varyEpsAExperimentAgesMode3[[3]][14,])[750], col="forestgreen", lwd=2, border=cols[3])

#horizontal: do it properly with lm
i=sort(
  apply(varyEpsAExperimentAgesMode3[[1]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  })
)[c(250, 750)]
rect(i[1], 4.7, i[2], 5.3, col="lightblue", lwd=2, border=cols[1])
i=sort(
  apply(varyEpsAExperimentAgesMode3[[2]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  })
)[c(250, 750)]
rect(i[1], 4.7, i[2], 5.3, col="lightblue", lwd=2, border=cols[2])
i=sort(
  apply(varyEpsAExperimentAgesMode3[[3]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  })
)[c(250, 750)]
rect(i[1], 4.7, i[2], 5.3, col="lightblue", lwd=2, border=cols[3])





i=sort(
  apply(varyEpsAExperimentAgesMode3[[3]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(10)))[1]
  })
)[c(250, 750)]
rect(i[1], 9.7, i[2], 10.3, col="cornflowerblue", lwd=2, border=cols[3])


i=sort(
  apply(varyEpsAExperimentAgesMode3[[1]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(10)))[1]
  })
)[c(250, 750)]
rect(i[1], 9.7, i[2], 10.3, col="cornflowerblue", lwd=2, border=cols[1])
i=sort(
  apply(varyEpsAExperimentAgesMode3[[2]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(10)))[1]
  })
)[c(250, 750)]
rect(i[1], 9.7, i[2], 10.3, col="cornflowerblue", lwd=2, border=cols[2])




#slice vertically: 
barplot(c(sapply(varyEpsBExperimentAges, function(i){
  sd(i[8,])
}), 
sapply(varyEpsBExperimentAges, function(i){
  sd(i[13,])
}),
sapply(varyEpsAExperimentAgesMode3, function(i){
  sd(i[8,])
}),

sapply(varyEpsAExperimentAgesMode3, function(i){
  sd(i[13,])
})
), col=cols, ylab="Standard deviation of biological age", xlab="Simulation", ylim=c(-0.2, 2))

rect(0.1, -0.1, 3.7, 0, col="lightgreen")
rect(3.7, -0.1, 3.7+3.6, 0, col="forestgreen")
rect(3.6+3.7, -0.1, 3.7+3.6+3.6, 0, col="lightgreen")
rect(3.6+3.6+3.7, -0.1, 3.7+3.6+3.6+3.6, 0, col="forestgreen")
rect(0.1, -0.2, 3.7+3.6, -0.1, col="grey")
rect(3.7+3.6, -0.2, 3.7+3.6*3, -0.1, col="lightyellow")



#slice horizontally

#barplot(c(sapply(varyEpsBExperimentAges, function(i){
#  sd(apply(i, 2, function(j){min(which(j>5))}))
#}), 
#sapply(varyEpsBExperimentAges, function(i){
#  sd(apply(i, 2, function(j){min(which(j>10))}))
#}),
#sapply(varyEpsAExperimentAgesMode3, function(i){
#  sd(apply(i, 2, function(j){min(which(j>5))}))
#}),

#sapply(varyEpsAExperimentAgesMode3, function(i){
#  sd(apply(i, 2, function(j){min(which(j>10))}))
#})
#), col=cols, ylab="Standard deviation of chronological age", xlab="Simulation", ylim=c(-0.2, 2))

barplot(c(sapply(varyEpsBExperimentAges, function(j){
  sd(apply(j, 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  }))
}),
sapply(varyEpsBExperimentAges, function(j){
  sd(apply(j, 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(10)))[1]
  }))
}),
sapply(varyEpsAExperimentAgesMode3, function(j){
  sd(apply(j, 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  }))
}),

sapply(varyEpsAExperimentAgesMode3, function(j){
  sd(apply(j, 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(10)))[1]
  }))
})), col=cols, ylab="Standard deviation of chronological age", xlab="Simulation", ylim=c(-0.2, 2))


i=sort(
  apply(varyEpsAExperimentAgesMode3[[2]], 2, function(i){
    xs=i
    ys=c(0:29)
    temp=lm(ys~xs, data=data.frame("xs"=xs, "ys"=ys))
    predict(temp, data.frame("xs"=c(5)))[1]
  })
)[c(250, 750)]
rect(0.1, -0.1, 3.7, 0, col="lightblue")
rect(3.7, -0.1, 3.7+3.6, 0, col="cornflowerblue")
rect(3.6+3.7, -0.1, 3.7+3.6+3.6, 0, col="lightblue")
rect(3.6+3.6+3.7, -0.1, 3.7+3.6+3.6+3.6, 0, col="cornflowerblue")
rect(0.1, -0.2, 3.7+3.6, -0.1, col="grey")
rect(3.7+3.6, -0.2, 3.7+3.6*3, -0.1, col="lightyellow")

dev.off()

###################
# as per reviewer feedback, draw sd and cv over time for simulations


png("plots/01_03_stDev_cv_over_time_sim.png", height=9, width=9, res=300, unit="in")
par(mfcol=c(2,2))
#with only starting point variation:

temp_var1=apply(varyEpsBExperimentAges[[1]], 1, function(j){c(sd(j), sd(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
plot(1:30, temp_var1[1,], col=cols[1], type="lines", lwd=2, ylim=c(0, 2), xlab="chronological time", ylab="standard deviation", main="starting point variation")


temp_var2=apply(varyEpsBExperimentAges[[2]], 1, function(j){c(sd(j), sd(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
lines(1:30, temp_var2[1,], col=cols[2], lwd=2)


temp_var3=apply(varyEpsBExperimentAges[[3]], 1, function(j){c(sd(j), sd(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
lines(1:30, temp_var3[1,], col=cols[3], lwd=2)


plot(1:30, temp_var1[2,], col=cols[1], type="lines", lwd=2, ylim=c(0, 0.5), xlab="chronological time", ylab="coefficient of variation")
lines(1:30, temp_var2[2,], col=cols[2], lwd=2)
lines(1:30, temp_var3[2,], col=cols[3], lwd=2)




#with maturation heterogeneity
temp_var1=apply(varyEpsAExperimentAgesMode3[[1]], 1, function(j){c(sd(j), sd(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
  plot(1:30, temp_var1[1,], col=cols[1], type="lines", lwd=2, ylim=c(0, 2), xlab="chronological time", ylab="standard deviation", main="maturation rate heterogeneity")
 
  
  temp_var2=apply(varyEpsAExperimentAgesMode3[[2]], 1, function(j){c(sd(j), sd(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
  lines(1:30, temp_var2[1,], col=cols[2], lwd=2)

  
  temp_var3=apply(varyEpsAExperimentAgesMode3[[3]], 1, function(j){c(sd(j), sd(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
  lines(1:30, temp_var3[1,], col=cols[3], lwd=2)
 
  
  plot(1:30, temp_var1[2,], col=cols[1], type="lines", lwd=2, ylim=c(0, 0.5), xlab="chronological time", ylab="coefficient of variation")
  lines(1:30, temp_var2[2,], col=cols[2], lwd=2)
  lines(1:30, temp_var3[2,], col=cols[3], lwd=2)
  


dev.off()

############################
# As per reviewer feedback, repeat this with Fano Factor
png("plots/01_03_var_FF_over_time_sim.png", height=9, width=9, res=300, unit="in")
par(mfcol=c(2,2))
#with only starting point variation:

temp_var1=apply(varyEpsBExperimentAges[[1]], 1, function(j){c(var(j), var(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
plot(1:30, temp_var1[1,], col=cols[1], type="lines", lwd=2, ylim=c(0, 2.3), xlab="chronological time", ylab="variance", main="starting point variation")


temp_var2=apply(varyEpsBExperimentAges[[2]], 1, function(j){c(var(j), var(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
lines(1:30, temp_var2[1,], col=cols[2], lwd=2)


temp_var3=apply(varyEpsBExperimentAges[[3]], 1, function(j){c(var(j), var(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
lines(1:30, temp_var3[1,], col=cols[3], lwd=2)


plot(1:30, temp_var1[2,], col=cols[1], type="lines", lwd=2, ylim=c(0, 0.5), xlab="chronological time", ylab="Fano Factor")
lines(1:30, temp_var2[2,], col=cols[2], lwd=2)
lines(1:30, temp_var3[2,], col=cols[3], lwd=2)




#with maturation heterogeneity
temp_var1=apply(varyEpsAExperimentAgesMode3[[1]], 1, function(j){c(var(j), var(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
plot(1:30, temp_var1[1,], col=cols[1], type="lines", lwd=2, ylim=c(0, 2), xlab="chronological time", ylab="variance", main="maturation rate heterogeneity")


temp_var2=apply(varyEpsAExperimentAgesMode3[[2]], 1, function(j){c(var(j), var(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
lines(1:30, temp_var2[1,], col=cols[2], lwd=2)


temp_var3=apply(varyEpsAExperimentAgesMode3[[3]], 1, function(j){c(var(j), var(j)/mean(j))})  #lines(1:50, j, col=cols_transparent[1])})
lines(1:30, temp_var3[1,], col=cols[3], lwd=2)


plot(1:30, temp_var1[2,], col=cols[1], type="lines", lwd=2, ylim=c(0, 0.5), xlab="chronological time", ylab="Fano Factor")
lines(1:30, temp_var2[2,], col=cols[2], lwd=2)
lines(1:30, temp_var3[2,], col=cols[3], lwd=2)



dev.off()




#############################
# as per reviewer feedback, use simulation to verify that 
# procedure used to align curves is legitimate


png(filename="plots/01_02_testAlignmentStrategy.png", width=8, height=8, res=300, units="in")
par(mfrow=c(2,2))
#simBoth=simulateInternalClocks(epsA=0, epsB=1, n=1000, ks=c(0.5, 1, 1.5), tp=c(0:30))
simBoth=simulateInternalClocks(epsA=0.1, epsB=1, n=1000, tp=c(0,30), ks=c(0.5, 1, 1.5), mode=3)
simMoreSpread=simulateInternalClocks(epsA=0.1, epsB=4, n=1000, tp=c(0,30), ks=c(0.5, 1, 1.5), mode=3)

#plot them


plot(c(), c(), xlim=c(0,28), ylim=c(0,29), xlab="Chronological time (days)", ylab="Biological age (days)")
tp=rep(0:30)
cols=c(rgb(1, 0.5,0.5,1),rgb(1, 0.7,0.2,1), rgb(0.8, 0.6,1,1))
cols_transparent=c(rgb(1, 0.5,0.5,0.2),rgb(1, 0.7,0.2,0.2), rgb(0.8, 0.6,1,0.2))
apply(simBoth[[1]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[1])})
apply(simBoth[[2]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[2])})
apply(simBoth[[3]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[3])})


plot(c(), c(), xlim=c(0,28), ylim=c(0,29), xlab="Chronological time (days)", ylab="Biological age (days)")
tp=rep(0:30)
cols=c(rgb(1, 0.5,0.5,1),rgb(1, 0.7,0.2,1), rgb(0.8, 0.6,1,1))
cols_transparent=c(rgb(1, 0.5,0.5,0.2),rgb(1, 0.7,0.2,0.2), rgb(0.8, 0.6,1,0.2))
apply(simMoreSpread[[1]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[1])})
apply(simMoreSpread[[2]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[2])})
apply(simMoreSpread[[3]][,1:50], 2, function(j){lines(0:29, j, col=cols_transparent[3])})
#############
#align simBoth in the same way as we do later with the barley data

# fit each curve to a line of best fit and then subtract by the intercept
x_intercepts=lapply(1:3, function(i){
  apply(simBoth[[i]], 2, function(j){
    intercept=lm(c(0:29)~j)$coefficients[1]
  })
})

#plot the simBoth again, but this time aligned
plot(c(), c(), xlim=c(0,28), ylim=c(0,29), xlab="Chronological time (days)", ylab="Biological age (days)")
tp=rep(0:30)
cols=c(rgb(1, 0.5,0.5,1),rgb(1, 0.7,0.2,1), rgb(0.8, 0.6,1,1))
cols_transparent=c(rgb(1, 0.5,0.5,0.2),rgb(1, 0.7,0.2,0.2), rgb(0.8, 0.6,1,0.2))

sapply(1:50, function(id){
  j=simBoth[[1]][,id]
  x=x_intercepts[[1]][id]
  lines(0:29-x, j, col=cols_transparent[1])
})

sapply(1:50, function(id){
  j=simBoth[[2]][,id]
  x=x_intercepts[[2]][id]
  lines(0:29-x, j, col=cols_transparent[2])
})

sapply(1:50, function(id){
  j=simBoth[[3]][,id]
  x=x_intercepts[[3]][id]
  lines(0:29-x, j, col=cols_transparent[3])
})

####Try it again with MoreSpread
# fit each curve to a line of best fit and then subtract by the intercept
x_intercepts=lapply(1:3, function(i){
  apply(simMoreSpread[[i]], 2, function(j){
    intercept=lm(c(0:29)~j)$coefficients[1]
  })
})

#plot the simMoreSpread again, but this time aligned
plot(c(), c(), xlim=c(0,28), ylim=c(0,29), xlab="Chronological time (days)", ylab="Biological age (days)")
tp=rep(0:30)
cols=c(rgb(1, 0.5,0.5,1),rgb(1, 0.7,0.2,1), rgb(0.8, 0.6,1,1))
cols_transparent=c(rgb(1, 0.5,0.5,0.2),rgb(1, 0.7,0.2,0.2), rgb(0.8, 0.6,1,0.2))

sapply(1:50, function(id){
  j=simMoreSpread[[1]][,id]
  x=x_intercepts[[1]][id]
  lines(0:29-x, j, col=cols_transparent[1])
})

sapply(1:50, function(id){
  j=simMoreSpread[[2]][,id]
  x=x_intercepts[[2]][id]
  lines(0:29-x, j, col=cols_transparent[2])
})

sapply(1:50, function(id){
  j=simMoreSpread[[3]][,id]
  x=x_intercepts[[3]][id]
  lines(0:29-x, j, col=cols_transparent[3])
})


dev.off()

